/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, errert, at https://www.jitblox.com/project/tMbg_90OGP/errert
*/

import { Routes } from '@angular/router';

export const routes: Routes = [
];
